fix: hide certain buttons on the TableToolBar from the viewer
undb-xyz/undb pull request #1432
Opened 2023-08-11 09:43 UTC by WanShufen

Hide certain buttons on the TableToolBar from the viewer.

![image](https://github.com/undb-xyz/undb/assets/73324423/0b779aad-a280-45b8-a7d2-73d6653b4390)

2023-08-11 14:50 UTC, nichenqin requested changes

2023-08-11 14:50 UTC, nichenqin commented on apps/frontend/src/lib/gallery/GalleryConfigMenu.svelte
> +{#if field && $hasPermission('record:create')}
这里不是 record:create 应该是 table:set_view_field，而且你也不应该隐藏，而是不能打开弹窗，因为我还是要看到这个视图是根据哪个表聚合的

2023-08-11 14:50 UTC, nichenqin commented on apps/frontend/src/lib/table/ManageFieldsMenu.svelte
> +{#if $hasPermission('table:toggle_field_visibility')}
这里也不能完全隐藏吧，我想看看表里有哪些列

2023-08-11 14:50 UTC, nichenqin commented on apps/frontend/src/lib/table/ManageFieldsMenu.svelte
> +{#if $hasPermission('table:toggle_field_visibility')}
打开的弹窗已经处理了权限了你看看

2023-08-11 14:50 UTC, nichenqin commented on apps/frontend/src/lib/table/TableMenu.svelte
> +	{#if $hasPermission('table:update')}
这里 1、不是 table:update 2、我也可以看的吧，因为我也想知道为什么我看不到某些行这个规则吧

2023-08-11 14:50 UTC, nichenqin commented on apps/frontend/src/lib/table/TableToolBar.svelte
> +		{#if $hasPermission('record:delete')}
这个地方不是 record:delete 你在做一个假设，他能删除行，就能看到被删除的行，其实这是两个不同的行为

2023-08-11 14:50 UTC, nichenqin commented on apps/frontend/src/lib/view/KanbanConfigMenu.svelte
> +{#if field && $hasPermission('record:create')}
这里也不是 record:create

2023-08-12 08:09 UTC, WanShufen commented on apps/frontend/src/lib/gallery/GalleryConfigMenu.svelte
> +{#if field && $hasPermission('record:create')}
现在已经在弹窗内做了限制了，如果没有 'table:set_view_field' 的权限，那这个弹窗内的radio 和创建按钮disabled

2023-08-12 08:14 UTC, WanShufen commented on apps/frontend/src/lib/table/ManageFieldsMenu.svelte
> +{#if $hasPermission('table:toggle_field_visibility')}
就我个人觉得，这里主要功能是对列配置做管理的，可能表的创建人隐藏了部分的字段，为啥隐藏的字段还要被其他人看见呢？而且明明这里就叫做 “配置列” 既然都是config了，那在viewer视图下不展示也很正常，表格界面上已经可以看见所有的字段了，退一万步来说就算列太多，viewer打开一个Record Modal不就可以看到所有的列信息了吗？Excel也没有一个地方统一去看所有列名字的啊

2023-08-12 09:22 UTC, WanShufen commented on apps/frontend/src/lib/table/TableToolBar.svelte
> +		{#if $hasPermission('record:delete')}
那要怎么做合理呢？一个查看者主要是上来查看现有数据的，而不是查看到谁做了什么操作导致最后数据结果是这样的，我认为在RBAC上面的权限力度就做简单点，因为还有RLS的配置

2023-08-12 09:30 UTC, nichenqin commented on apps/frontend/src/lib/table/TableToolBar.svelte
> +		{#if $hasPermission('record:delete')}
这里做的行为是「查看回收站」，那你检查的权限就应该是「查看回收站」呀，就是要简单点

2023-08-12 09:30 UTC, nichenqin commented on apps/frontend/src/lib/gallery/GalleryConfigMenu.svelte
> +{#if field && $hasPermission('record:create')}
那也不是 record:create 呀

2023-08-12 16:53 UTC, nichenqin requested changes

2023-08-12 16:53 UTC, nichenqin commented on apps/frontend/src/lib/table/TableToolBar.svelte
> +		{#if $hasPermission('table:create_form')}
这里是list form

2023-08-12 16:53 UTC, nichenqin commented on packages/cqrs/src/commands/set-row-height/set-row-height.command.handler.test.ts
> +describe('setRowHeight', () => {
这个先别上传吧

2023-08-13 11:25 UTC, nichenqin requested changes

2023-08-13 11:25 UTC, nichenqin commented on apps/frontend/src/lib/view/KanbanConfigMenu.svelte
> +<!-- {#if field && $hasPermission('record:create')} -->
这里也不是 record:create

2023-08-13 15:04 UTC, nichenqin approved these changes

2023-08-13 15:12 UTC, merged